name: dev
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup code
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: check
