name: stg
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Package for windows
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          powershell Compress-Archive -Path target/${{ matrix.target }}/release/hekopanda.exe -DestinationPath hekopanda-${{ matrix.target }}.zip
      - name: Package for macOS
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          zip --junk-paths hekopanda-${{ matrix.target }} target/${{ matrix.target }}/release/hekopanda
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.target }}
          path: hekopanda-${{ matrix.target }}.zip
